### ISSUE TITLE
Charts not using the database credentials

### ISSUE THREAD

**Issue by Sgitario** [quarkus-qe/quarkus-catalog-apps#36]
At the moment, the chart looks like:

```

# Default values for paths-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
qe-quarkus-app:
  replicaCount: 1
  deployment:
    // ...
    env:
      - name: QUARKUS_DATASOURCE_JDBC_URL
        value: jdbc:postgresql://dev-quarkusappcatalog.postgresql-qe-infra:5432/quarkusappcatalog
      - name: QUARKUS_DATASOURCE_USERNAME
        value: root
      - name: QUARKUS_DATASOURCE_PASSWORD
        value: root
    // ...
  service:
    // ...
  database:
    url: jdbc:postgresql://dev-quarkusappcatalog.postgresql-qe-infra:5432/quarkusappcatalog
    user: root
    pwd: EWQNNZC
    schema: quarkusappcatalog
  kafka:
    // ...
```

The environment variables are wrong and making the services fail (because of a wrong credential), the right credentials are in database section which seems to be ignored. 

FYI: I will workaround this issue by updating the environment variables, but I guess the right fix is to get rid of the environment variables and use the database section.
